language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2.0

before_script:
  - composer install --dev --no-interaction

script:
  - phpunit --configuration phpunit.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
